# docker-compose.yml

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://mongodb:27017/corebank_db
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["mongod", "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge